# Generated by Django 4.1.4 on 2023-01-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
